# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

# trigger:
# - dev


parameters:
  - name: Env
    type: string
    default: 'dev'
    values:
      - dev
      - uat
      - prod


variables:
  - group: advwrks22-vg-kv  # variable group reference
  - name: resourceGroup     # individual variables
    value: 'adventureworks-22-proj-rg'
  - name: dataFactory
    value: 'adventureworks-22-proj-adf'
  - name: parameterFileName
    value: 'adf-parameters.${{ parameters.Env }}.json'

pool:
  vmImage: ubuntu-latest

resources:
  pipelines:
  - pipeline: azure-pipelines
    source: rachitg-code.az-dataengg-repo-advwrks-adf-publish
    branch: dev
    # trigger:
    #   branches:
    #     include:
    #     - dev

stages:
  - stage: Deploy_to_Adf_Dev
    displayName: 'Deploy to ADF - Dev Environment'
    jobs:
      - deployment: Deploy_Adf_Arm_Template
        displayName: 'Deploy ADF Arm Template to Dev'
        environment: 'adf-dev'
        strategy:
          runOnce:
            deploy:
              steps:
                - download: azure-pipelines
                  artifact: ArmTemplate
                - script: |
                    echo "CI build ID: " $(resources.pipeline.azure-pipelines.runID)
                    echo "CI build number: " $(resources.pipeline.azure-pipelines.runName)
                  displayName: 'CI Build Info'
                - script: |
                    ls -R $(Pipeline.Workspace)
                  displayName: 'debug'
                - task: AzureResourceManagerTemplateDeployment@3
                  displayName: 'Deploy ADF (Dev)'
                  inputs:
                    deploymentScope: 'Resource Group'
                    azureResourceManagerConnection: 'rachitg-dataengg (c38c0101-2c45-4838-b14a-9411d616169b)'
                    subscriptionId: $(advwrks22-adf-sbscr-id)
                    action: 'Create Or Update Resource Group'
                    resourceGroupName: $(resourceGroup)
                    Location: 'South India'
                    templateLocation: 'Linked artifact'
                    csmFile: '$(Pipeline.Workspace)/azure-pipelines/ArmTemplate/ARMTemplateForFactory.json'
                    csmParametersFile: '$(Pipeline.Workspace)/azure-pipelines/ArmTemplate/$(parameterFileName)'

                    #csmParametersFile: '$(Pipeline.Workspace)/azure-pipelines/ArmTemplate/ARMTemplateParametersForFactory.json'
